###
GET https://localhost:7160/person

###
GET https://localhost:7160/person/3a8d4319-7c29-4805-b61e-28210f7d33b9

###
POST https://localhost:7160/person/create
Content-Type: application/json
{
  "firstName": "Mark",
  "lastName": "Hazelton",
  "age": 35,
  "email": "mark@frogsfolly.com"}

###
POST https://localhost:7160/person/create
Content-Type: application/json
{
  "firstName": "Lesley",
  "lastName": "Hazelton",
  "age": 36,
  "email": "lesley@frogsfolly.com"}

###
PUT https://localhost:7160/person/update/f183fdae-90a6-4178-8b86-61ffc2b68b6b
Content-Type: application/json
{
  "id": "f183fdae-90a6-4178-8b86-61ffc2b68b6b",
  "firstName": "Lesley",
  "lastName": "Hazleton",
  "age": 36,
  "email": "lesley@texecon.com"}

 ###
 DELETE https://localhost:7160/person/b6b21a2b-f605-434a-a973-d43ddef5d38c

 ###