# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - FastEndpointsDemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  AZURE_WEBAPP_NAME: 'FastEndpointsDemo'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"
        continue-on-error: true

      - name: Publish application
        run: dotnet publish -c ${{ env.CONFIGURATION }} -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          retention-days: 1
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5343C5D6FF75422682FD58410448149F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_78AB16DB07CA4E4FBA556DEAB327B5FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_68D7EA995B174718AA4FDAF7EB16838E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Logout from Azure
        if: always()
        run: az logout